# Generated by Django 5.0.6 on 2024-06-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('side', models.CharField(blank=True, max_length=10, null=True)),
                ('orderType', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('triggerPrice', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('Exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('takeProfit', models.CharField(blank=True, max_length=50, null=True)),
                ('stopLoss', models.CharField(blank=True, max_length=50, null=True)),
                ('reduceOnly', models.CharField(blank=True, max_length=50, null=True)),
                ('botOrderType', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
